# Generated by Django 4.2.6 on 2024-03-10 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingadress',
            name='city',
        ),
    ]
