# Generated by Django 4.2.6 on 2024-03-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_description_product_old_price_product_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='this is a product', null=True),
        ),
    ]
