# Generated by Django 4.2.6 on 2024-03-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_product_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orders_count',
            field=models.IntegerField(default=0),
        ),
    ]
