# Generated by Django 4.2.6 on 2024-03-21 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_feature_varient_remove_productcolor_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagerelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='related_product/')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.productimage')),
            ],
        ),
    ]
