# Generated by Django 4.2.6 on 2024-03-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_imagerelated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='Imagerelated',
            new_name='Related',
        ),
    ]
