# Generated by Django 4.2.6 on 2024-03-23 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_delete_related'),
    ]

    operations = [
        migrations.RenameField(
            model_name='varient',
            old_name='color',
            new_name='colors',
        ),
        migrations.AlterField(
            model_name='varient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varient', to='store.product'),
        ),
    ]
