# Generated by Django 4.2.6 on 2024-03-24 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Customer',
            new_name='customer',
        ),
    ]
