# Generated by Django 4.2.6 on 2024-03-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_rename_customer_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
