# Generated by Django 4.2.6 on 2024-03-26 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_customer_phone_shippingadress_address_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingadress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='shippingadress',
            name='state',
        ),
    ]
